_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${savedir}
log_every_n_steps: 1

min_epochs: 100
max_epochs: 1000000

accelerator: gpu
devices: null
strategy: ddp
# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 100

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
limit_val_batches: 0.0 #turn thisthis on in case you do not need validation