_target_: script.evaluator.celebahq_evaluator.CelebAHQEvaluator
ae_config: "${rootdir}/autoencoder_ckpts/first_stage_models/vq-f4/config.yaml"
ae_ckpt: "${rootdir}/autoencoder_ckpts/first_stage_models/vq-f4/model.ckpt"
timesteps: 10
img_path: ${rootdir}/celeba_evaluation/${modelname}
initial_path: "${rootdir}/datasets/celebADialogEmbbeded_eval"
targc: [[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0],
       [0, 1],
       [1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1],
       [0, 2],
       [1, 2],
       [2, 2],
       [3, 2],
       [4, 2],
       [5, 2],
       [0, 3],
       [1, 3],
       [2, 3],
       [3, 3],
       [4, 3],
       [5, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [3, 4],
       [4, 4],
       [5, 4],
       [0, 5],
       [1, 5],
       [2, 5],
       [3, 5],
       [4, 5],
       [5, 5]]
c_indecies: [3,2]