_target_: script.evaluator.drug_evaluator.ZINC22_2DimEvaluator
autoencoder_path: ${rootdir}/autoencoder_ckpts/general_doc.pt
cond_cdf_path: ${rootdir}/datasets/ZINC22_preprocessed_logp_tpsa/cond_cdfs.pkl 
device: cuda
emb_name: emb_smiles
c_emb_name: ["logp","tpsa"]
initial_point_dir: ${rootdir}/data/zinc22_logp_tpsa_eval.npz
validation_conds: [[  0.,  10.],
       [  1.,  10.],
       [  2.,  10.],
       [  3.,  10.],
       [  4.,  10.],
       [  0.,  45.],
       [  1.,  45.],
       [  2.,  45.],
       [  3.,  45.],
       [  4.,  45.],
       [  0.,  80.],
       [  1.,  80.],
       [  2.,  80.],
       [  3.,  80.],
       [  4.,  80.],
       [  0., 115.],
       [  1., 115.],
       [  2., 115.],
       [  3., 115.],
       [  4., 115.],
       [  0., 150.],
       [  1., 150.],
       [  2., 150.],
       [  3., 150.],
       [  4., 150.]]
num_seed: 10
noise_intensity: 0.1
cdf_names: ["cdf_logp","cdf_tpsa"]