_target_: stochastic_interpolant.models.VelocityFieldModel
model:
  _target_: stochastic_interpolant.models.DeepDenseNet
  w: 128
  activation: SELU
  depth: 8
  normalize: False
  model_input_dim: 3
  model_output_dim: 2