dataset1:
  _target_: script.datasets.zinc22_dataset.ZINC22_Dataset
  preprocessed_root: ${rootdir}/datasets/ZINC22_preprocessed_lowqed_subsampled_b1024/
  x_name: emb_smiles
  cond_columns: ["cdfd_qed"]
  upto: null
dataset2:
  _target_: script.datasets.zinc22_dataset.ZINC22_Dataset
  preprocessed_root: ${rootdir}/datasets/ZINC22_preprocessed_highqed_subsampled_b1024/
  x_name: emb_smiles
  cond_columns: ["cdfd_qed"]
  upto: null